# Generated by Django 2.0.2 on 2018-02-04 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180204_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
